name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  build_linux:
    name: Build Flutter (Linux)
    needs: [flutter-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"        
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build linux
