name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 
    tags:
      - 'latest'

jobs: 
  build:
    name: Build Flutter (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"     
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev   
      - run: flutter pub get
      - run: flutter clean
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/linux/x64/release/bundle/*"
          tag

